### ISSUE TITLE
How can I get the result of the validation compliance test?

### ISSUE THREAD

**Issue by lenaxus** [admin-shell-io/aas-test-engines#3] opened 2023-11-21 07:55 UTC
## Expected Behavior

I want to check my AAS to prove if it is Metamodel Version 3 confirm. I have choosen the variant to check json data directly.

## Actual Behavior

The script is running but I never got any result information. I tried valid AASes and non-valid AASes.

## Steps to Reproduce the Problem

  1. Here is my script to check a non-valid AAS:
````
from aas_test_engines import file

print('I am in')

# Or check data directly
aas = {
    'assetAdministrationShells': [
        {
            "extension": [
                {
                    "semanticId": {
                        "type": "ExternalReference",
                        "keys": [
                        {
                            "type": "GlobalReference",
                            "value": ""
                        }
                        ]
                    },
                    "name": "MaterialNumber",
                    "valueType": "xs:string",
                    "value": ""
                },
                {
                    "semanticId": {
                        "type": "ExternalReference",
                        "keys": [
                        {
                            "type": "GlobalReference",
                            "value": ""
                        }
                        ]
                    },
                    "name": "Author",
                    "valueType": "xs:string",
                    "value": ""
                },
                {
                    "semanticId": {
                        "type": "ExternalReference",
                        "keys": [
                        {
                            "type": "GlobalReference",
                            "value": ""
                        }
                        ]
                    },
                    "name": "CreationDate",
                    "valueType": "xs:dateTime",
                    "value": ""
                }
            ],
            "administration": {
                "version": "1",
                "revision": "0"
            }
  }
    ],
    'submodels': [],
    'conceptDescriptions': []
}
file.check_json_data(aas)

print('I am finished')
````

The output is the following: 
```
I am in
I am finished
```

Here you can see that the one AAS which is included only has the 'extension' prop and because should not be valid at all? Can anybody help me here?

**Comment by lenaxus** [comment] 2023-12-01 08:23
Hi @otto-ifak, thank you for your reply. It works now, I got the result :)

I am getting now the output: 
```Check JSON
   Does not match all sub-schemas
      Reference #/$defs/Environment is invalid
         Property assetAdministrationShells is invalid
            item 0 is invalid
         Property submodels is invalid
            Array is shorter than 1
         Property conceptDescriptions is invalid
            Array is shorter than 1```
       
So it seems that my inserted AAS which should be valid (it is a different one from above) is invalid. Is it possible that you can give here more insights why it is invalid? That would be very helpful!

**Comment by otto-ifak** [comment] 2024-01-26 09:11
The arrays 'assetAdministrationShells',  `submodels` and `conceptDescriptions` are not allowed to be empty:
https://github.com/admin-shell-io/aas-specs/blob/f4662a61cb7cdb180a779da38b409e7ead749628/schemas/json/aas.json#L582

Additionally: we planned to address https://github.com/admin-shell-io/aas-test-engines/issues/4 next week, this will provide you with more details when a file is rejected.

**Comment by otto-ifak** [comment] 2024-02-01 07:11
Hi @lenaxus, we updated the underlying JSON schema library, so that you get much more information now:

```
Check JSON
   Does not match all sub-schemas
      Reference #/$defs/Environment is invalid
         Property assetAdministrationShells is invalid
            item 0 is invalid
               Reference #/$defs/AssetAdministrationShell is invalid
                  Does not match all sub-schemas
                     Property assetInformation is invalid
                        Reference #/$defs/AssetInformation is invalid
                           Does not match all sub-schemas
                              Reference #/$defs/Constraint_AASd-131 is invalid
                                 Does not match exactly one sub-schema
                                    Does not match all sub-schemas
                                       Property specificAssetIds is missing
                                    Does not match all sub-schemas
                                       Property globalAssetId is missing
                     Property submodels is invalid
                        Array is shorter than 1
```

The problem is that your AAS violates constraint AASd-131: The globalAssetId or at least one specificAssetId shall be defined for AssetInformation.

**Comment by otto-ifak** [comment] 2024-02-01 07:27
Marking this as closed, please continue discussion in https://github.com/admin-shell-io/aas-test-engines/issues/6

**Closed** 2024-02-01 07:27 UTC
